repos:
  - repo: https://github.com/prettier/prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        files: \.(tsx|js|ts|json|go|css|md)$

  - repo: https://github.com/eslint/eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.(js|ts|jsx|tsx)$

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.42.0
    hooks:
      - id: golangci-lint
        language: golang
        files: \.go$
