
services:
  client:
    image: node:16  # Use Node.js image for building the client
    working_dir: /app
    volumes:
      - ./client:/app  # Mount the client directory
    command: >
      sh -c "npm install && npm run build"  # Install dependencies and build

  server:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this points to the correct Dockerfile for the server
    ports:
      - '3001:3001'  # Expose server on port 3000
    environment:
      - GO_ENV=development
      - DB_CONFIG=postgresql://user:password@db:5432/dbname  # Update with your DB credentials
      - PORT=:3000
      - SECRET=asdasdwqe123
    depends_on:
      - db  # Ensure the db service is started before the server
    volumes:
      - .:/app  # Mount the entire project directory for development

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user  # Update with your DB username
      - POSTGRES_PASSWORD=password  # Update with your DB password
      - POSTGRES_DB=dbname  # Update with your DB name
    ports:
      - '5432:5432'  # Expose PostgreSQL on port 5432
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data

networks:
  default:
    driver: bridge

volumes:
  db_data:  # Define a volume for PostgreSQL data persistence

