services:
  client:
    image: node:23
    working_dir: /app
    volumes:
      - ./client:/app  
    environment:
      - VITE_API=https://nehar.online
    command: >
      sh -c "npm install && npm run build"  # Install dependencies and build

  server:
    image: golang:1.23  
    working_dir: /app
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - GO_ENV=development
      - DB_CONFIG=postgresql://user:password@db:5432/dbname
      - PORT=:3001
      - SECRET=asdasdwqe123
      - API=https://nehar.online
    command: >
      sh -c "go mod tidy && go install github.com/air-verse/air@latest && air"  # Install dependencies and run air
    ports:
      - '3001:3001'  
    depends_on:
      - db  
      - client
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user  
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=dbname  
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data  

networks:
  default:
    driver: bridge

volumes:
  db_data:  # Define a volume for PostgreSQL data persistence

